### ISSUE TITLE
d3_nest() fails with dev tidyr

### ISSUE THREAD

**Issue by hadley** [timelyportfolio/d3r#13]
```R
library(d3r)

titanic_df <- Titanic %>% 
  data.frame() %>% 
  select(Class,Age,Survived,Sex,Freq)

d3_nest(titanic_df, value_cols="Freq", root="titanic")
#> Error: No tidyselect variables were registered
```

Would you mind taking a look? It's probably because I've accidentally broken some aspect of `nest()`, but I can't quite figure out what the code is supposed to be doing

**Comment by timelyportfolio** [comment]
@hadley I fixed with https://github.com/timelyportfolio/d3r/commit/4b276b3e95810f11fd309d0a8e2da3d93c97107e.  I assume I will wait for newest `tidyr` to hit CRAN and then submit this new version of `d3r` to CRAN.

**Comment by hadley** [comment]
What was the root cause of the problem?

**Comment by timelyportfolio** [comment]
I ended up rewriting to work with new version, but I believe I could have fixed by changing the named argument `data = ` to `.data =`.

**Comment by jennybc** [comment]
In our revdep check and my local efforts, https://github.com/timelyportfolio/d3r/commit/4b276b3e95810f11fd309d0a8e2da3d93c97107e does not seem to actually fix the problem.

I've made another PR that does. Good news: small change! Bad news: requires dev tidyr. I lay out the options for next steps in the PR.

**Comment by jennybc** [comment]
Fixing this should also fix echarts4r and sunburstR:

https://github.com/tidyverse/tidyr/blob/master/revdep/problems.md#echarts4r

https://github.com/tidyverse/tidyr/blob/master/revdep/problems.md#sunburstr

**Comment by timelyportfolio** [comment]
@hadley @jennybc this should now be fixed to work with both old and new `tidyr` syntax and has been released on CRAN.  Thanks for all your help.

I know `sunburstR` is definitely solved with this change and fairly confident `echarts4r` will be fixed as well.

Please reopen if not solved.
