### ISSUE TITLE
Problems with Tidyr 

### ISSUE THREAD

**Issue by joseraymar** [timelyportfolio/d3r#17]
Hi, I have a Issue with Tidyr  `nest_()` was deprecated in tidyr 1.0.0 and is now defunct and the package use nest in d3r_party function. Could you change this please, thanks.

**Comment by MTada7140** [comment]
I faced the same issue. Can anyone please fix this? Thanks.

**Comment by timelyportfolio** [comment]
I have fixed on Github, but unfortunately these changes require a more extensive set of other changes before I can get to CRAN.  If possible, for now please `remotes::install_github("timelyportfolio/d3r")`.

**Comment by timelyportfolio** [comment]
@joseraymar @mtada7140 should now be fixed and on CRAN.  Please report any issues and feel free to reopen.
